[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true
gas_reports = ["*"]
verbosity = 3

[rpc_endpoints]
tenderly_sonic = "${TENDERLY_SONIC_RPC_URL}"

[etherscan]
sonic = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.sonic.rpc.tenderly.co" }

[profile.tenderly]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
# via_ir = true
gas_reports = ["*"]

# Compiler settings - more memory for complex contracts
# memory_limit = 33554432 # 32 * 1024 * 1024
ffi = true 
fs_permissions = [{ access = "read-write", path = "./"}]

# For Tenderly simulation
[profile.tenderly.rpc_storage_caching]
chains = "all"
endpoints = "all"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
